# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labmanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from information import *
from sql import *


class Manager_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(639, 510)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 111, 23))
        self.pushButton.clicked.connect(self.lab_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 111, 23))
        self.pushButton_2.clicked.connect(self.course_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 100, 111, 23))
        self.pushButton_3.clicked.connect(self.teacher_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 140, 111, 23))
        self.pushButton_4.clicked.connect(self.student_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 180, 111, 23))
        self.pushButton_5.clicked.connect(self.software_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 360, 111, 23))
        self.pushButton_6.clicked.connect(self.update_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 400, 111, 23))
        self.pushButton_7.clicked.connect(self.delete_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 440, 111, 23))
        self.pushButton_8.clicked.connect(self.insert_info)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(150, 20, 481, 411))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 260, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "管理员专用页面"))
        self.pushButton.setText(_translate("Dialog", "查看实验室信息"))
        self.pushButton_2.setText(_translate("Dialog", "查看课程信息"))
        self.pushButton_3.setText(_translate("Dialog", "查看教师信息"))
        self.pushButton_4.setText(_translate("Dialog", "查看学生信息"))
        self.pushButton_5.setText(_translate("Dialog", "查看软件信息"))
        self.pushButton_6.setText(_translate("Dialog", "更新信息"))
        self.pushButton_7.setText(_translate("Dialog", "删除选中行"))
        self.pushButton_8.setText(_translate("Dialog", "增加一行"))
        self.label.setText(_translate("Dialog", "  欢迎回来！"))
        self.label_2.setText(_translate("Dialog", "   管理员"))
        self.label_3.setText(_translate("Dialog", "   尊敬的"))

    def lab_info(self):
        self.model = lab_model
        self.tableView.setModel(self.model)
        self.tableView.setObjectName("LabView")

    def course_info(self):
        self.model = course_model
        self.tableView.setModel(self.model)
        self.tableView.setObjectName("CourseView")

    def teacher_info(self):
        self.model = teacher_model
        self.tableView.setModel(self.model)
        self.tableView.setObjectName("TeacherView")

    def student_info(self):
        self.model = student_model
        self.tableView.setModel(self.model)
        self.tableView.setObjectName("StudentView")

    def software_info(self):
        self.model = software_model
        self.tableView.setModel(self.model)
        self.tableView.setObjectName("SoftwareView")

    def update_info(self):
        db.ping(reconnect=True)
        cheat(cursor)
        # 更新实验室信息
        if self.tableView.objectName() == "LabView":
            for i in range(self.model.columnCount()):
                if i == 0:
                    continue
                if i == 1:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.lab SET m_id = '" + t + "' WHERE lab_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 2:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.lab SET lab_name = '" + t + "' WHERE lab_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 3:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.lab SET lab_address = '" + t + "' WHERE lab_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 4:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.lab SET lab_area = '" + t + "' WHERE lab_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 5:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.lab SET lab_numbers = '" + t + "' WHERE lab_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 6:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.lab SET lab_computer = '" + t + "' WHERE lab_id = '" + r + "';"
                        cursor.execute(usql)

        # 更新课程信息
        if self.tableView.objectName() == "CourseView":
            for i in range(self.model.columnCount()):
                if i == 0:
                    continue
                if i == 1:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.course SET lab_id = '" + t + "' WHERE c_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 2:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.course SET c_name = '" + t + "' WHERE c_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 3:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.course SET c_teacher = '" + t + "' WHERE c_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 4:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.course SET c_hours = '" + t + "' WHERE c_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 5:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.course SET c_credit = '" + t + "' WHERE c_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 6:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.course SET c_numbers = '" + t + "' WHERE c_id = '" + r + "';"
                        cursor.execute(usql)

        #更新软件信息
        if self.tableView.objectName() == "SoftwareView":
            for i in range(self.model.columnCount()):
                if i == 0:
                    continue;
                if i == 1:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.software SET t_id = '" + t + "' WHERE s_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 2:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.software SET s_name = '" + t + "' WHERE s_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 3:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.software SET s_version = '" + t + "' WHERE s_id = '" + r + "';"
                        cursor.execute(usql)
                if i == 4:
                    for j in range(self.model.rowCount()):
                        t = self.model.item(j, i).text()
                        r = self.model.item(j, 0).text()
                        usql = "UPDATE lab.software SET s_volume = '" + t + "' WHERE s_id = '" + r + "';"
                        cursor.execute(usql)

        db.commit()

    def delete_info(self):
        db.ping(reconnect=True)
        cheat(cursor)
        try:
            indices = self.tableView.selectionModel().selectedRows()
        except:
            return
        for index in sorted(indices):
            r = self.model.item(index.row(), 0).text()
            self.model.removeRow(index.row())
        # 删除实验室信息
        if self.tableView.objectName() == "LabView":
            dsql = "DELETE FROM lab WHERE lab_id = '" + r + "';"
            cursor.execute(dsql)
        #删除课程信息
        elif self.tableView.objectName() == "CourseView":
            dsql = "DELETE FROM course WHERE c_id = '" + r + "';"
            cursor.execute(dsql)
        #删除软件信息
        elif self.tableView.objectName() == "SoftwareView":
            dsql = "DELETE FROM software WHERE s_id = '" + r + "';"
            cursor.execute(dsql)
        else:
            return
        db.commit()

    def insert_info(self):
        #这个按钮功能实际上是插入一条空字段，实际实现是通过update按钮
        db.ping(reconnect=True)
        cheat(cursor)
        #插入一条实验室信息
        if self.tableView.objectName() == "LabView":
            r = self.model.item(self.model.rowCount() - 1, 0).text()
            if r == '09':
                r1 = '10'
            elif r[0] == '0':
                r1 = '0' + str(int(r[1]) + 1)
            else:
                r1 = str(int(r) + 1)
            self.model.appendRow(QStandardItem(r1))
            isql = "INSERT INTO lab VALUES ('" + r1 + "','000000001','1','1','1','1','1');"
            cursor.execute(isql)
        #插入一条课程信息
        elif self.tableView.objectName() == "CourseView":
            r = self.model.item(self.model.rowCount() - 1, 0).text()
            if r == '09':
                r1 = '10'
            elif r[0] == '0':
                r1 = '0' + str(int(r[1]) + 1)
            else:
                r1 = str(int(r) + 1)
            self.model.appendRow(QStandardItem(r1))
            isql = "INSERT INTO course VALUES ('" + r1 + "','99','1','1','1','1','1');"
            cursor.execute(isql)
        #插入一条软件信息
        elif self.tableView.objectName() == "SoftwareView":
            r = self.model.item(self.model.rowCount() - 1, 0).text()
            if r == '09':
                r1 = '10'
            elif r[0] == '0':
                r1 = '0' + str(int(r[1]) + 1)
            else:
                r1 = str(int(r) + 1)
            self.model.appendRow(QStandardItem(r1))
            isql = "INSERT INTO software VALUES ('" + r1 + "','01','1','1','1');"
            cursor.execute(isql)
        else:
            return
        db.commit()

