# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from sql import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from labmanager import Manager_Dialog
from labteacher import Teacher_Dialog
from labstudent import Student_Dialog

class Login_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.login)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "登录"))
        self.label.setText(_translate("Dialog", "请输入你的账号："))
        self.pushButton.setText(_translate("Dialog", "OK"))

    def login(self):

        self.form_manager = QWidget()
        self.Manager = Manager_Dialog()
        self.Manager.setupUi(self.form_manager)

        self.form_teacher = QWidget()
        self.Teacher = Teacher_Dialog()
        self.Teacher.line = self.lineEdit.text()
        self.Teacher.setupUi(self.form_teacher)

        self.form_student = QWidget()
        self.Student = Student_Dialog()
        self.Student.line = self.lineEdit.text()
        self.Student.setupUi(self.form_student)

        if self.lineEdit.text() in Login_Accept_Manager:
            self.form_manager.show()
        elif self.lineEdit.text() in Login_Accept_Teacher:
            self.form_teacher.show()
        elif self.lineEdit.text() in Login_Accept_Student:
            self.form_student.show()
        else:
            self.lineEdit.clear()

